name: turbo_mvvm
description: A lightweight MVVM state management solution inspired by the FilledStacks Stacked package.
version: 1.3.0
resolution: workspace
repository: https://github.com/appboypov/turbo_packages/tree/main/turbo_mvvm
homepage: https://github.com/appboypov/turbo_packages
issue_tracker: https://github.com/appboypov/turbo_packages/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  gherkin_unit_test: ^0.0.5
  gherkin_integration_test: ^0.0.5
  coverage: ^1.15.0

flutter:
